user_input = input("Type something: ")
print(f"Data type: {type(user_input)}")
print(f"Only spaces: {user_input.isspace()}")
print(f"It's a number: {user_input.isnumeric()}")
print(f"It's alphabetic: {user_input.isalpha()}")
print(f"It's alphanumeric: {user_input.isalnum()}")
print(f"It's uppercase: {user_input.isupper()}")
print(f"It's lowercase: {user_input.islower()}")
print(f"It's capitalized: {user_input.istitle()}")